Clim data updates
tcarleton/stagg pull request #26
Opened 2023-10-31 17:55 UTC by traceybit

updated code to be more flexible and allow for different kinds of inputs, replaced if statements with case when. some of these updates were completed to address issue described in #21

2023-10-31 22:47 UTC, saraorofino requested changes

2023-11-01 06:09 UTC, traceybit commented on R/overlay_weights.R
> +    ## this doesn't work with dt... figure out or delete and use above
i wanted to keep this for now because i wanted to try to get it in data.table (probably in the same effort to convert things to the terra package)

2023-11-01 06:11 UTC, traceybit commented on R/overlay_weights.R
> +    w_norm <- data.table::copy(area_weight)
oops replaced `area_weight` with `w_norm` on line 199

2023-11-01 06:15 UTC, traceybit commented on R/overlay_weights.R
> +        stop(crayon::red('Weights for polygon', check_weights$poly_id[i], 'do not sum to 1')) }
made suggested change

2023-11-01 06:16 UTC, traceybit commented on R/overlay_weights.R
> +      message(crayon::yellow('Adjusting secondary weights longitude -180 to 180.'))
made suggested change

2023-11-01 06:17 UTC, traceybit commented on R/secondary_weights.R
> +    message(crayon::yellow('Longitude coordinates do not match. Aligning longitudes to -180 to 180.'))
made suggested change

2023-11-01 06:18 UTC, traceybit commented on R/secondary_weights.R
> +    message(crayon::yellow('Longitude coordinates do not match. Aligning longitudes to -180 to 180.'))
made suggested change

2023-11-01 06:30 UTC, traceybit commented on R/staggregate.R
> +    }
so i think that the nested if statements should be right here, but perhaps i implemented it incorrectly... here is a description of what i tried to implement here:

- starting on line 45, if xmin of the climate raster is < 0 (and thus not in 0 to 360 format...
- {create clim_raster1, which is the part of the climate raster with negative x values. shift to 0-360 format. these are lines 47-54.
- line 56, start new if statement. if xmax > 0, 
- {lines 57-61, crop clim_raster to the part with x values  >= 0 and merge that with clim_raster1 to create clim_raster}
- but if xmax is not > 0 , clim_raster = just clim_raster1 (lines 62-65)
-  close if statement that started on line 45 (so if xmin of clim_raster was not < 0, clim_raster shoudl just be clim_raster

doest that make sense? i noticed and error in the climate raster name in one of the lines so i fixed that. let me know if you thin this description makes sense.

2023-11-01 06:31 UTC, traceybit commented on R/staggregate.R
> +
oops yes fixed this!

2023-11-01 19:25 UTC, saraorofino commented on R/staggregate.R
> +    }
Yes okay thanks for explanation -  this does look right. I missed the `}` on line 67 so wasn't realizing that the other `if/else` was contained within the first `if` statement on line 45.

2023-11-01 19:25 UTC, saraorofino approved these changes
Looks good now thanks for making those additional changes!

2023-11-01 19:47 UTC, merged